### ISSUE TITLE
Missing closing bracket

### ISSUE THREAD

**Issue by gavinmcfarland** [rajasegar/compack#1]
Running `compact -create my-component` didn't work me and I found a bracket was missing on line 211 of compact.js. However after fixing it I'm still not able to run the command. I get the following error message:

```
Creating component:  /Users/sevenupcan/Sites/testing__compack/my-component
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/sevenupcan/Sites/testing__compack/my-component/test.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Compack.write (/usr/local/lib/node_modules/compack/lib/compack.js:249:12)
    at Compack.createComponent (/usr/local/lib/node_modules/compack/lib/compack.js:215:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/compack/bin/compack:91:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by rajasegar** [comment]
Fixed it here
https://github.com/rajasegar/compack/commit/183b26519d43de740b6bfab67024e3ab303823ba

**Comment by gavinmcfarland** [comment]
Thanks it works now. Really great tool by the way, thank you. Would be interesting if you could add support for Polymer by being able add dependencies for components.

**Comment by rajasegar** [comment]
Thanks for the appreciation Gavin, i will add this to the list of
milestones, looking forward to include this in the future versions...

On Mon, Mar 14, 2016 at 9:58 PM, Gavin McFarland notifications@github.com
wrote:

> Thanks it works now. Really great tool by the way, thank you. Would be
> interesting if you could add support for Polymer by being able add
> dependencies for components.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rajasegar/compack/issues/1#issuecomment-196398635.

## 

Regards & Thanks,
Rajasegar Chandiran
www.hangaroundtheweb.com
